name: CI - Build, Test & Push Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write    # required for OIDC
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: color-palette-api

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app/service

    steps:
      # ----------------------------
      # Checkout source code
      # ----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------
      # Node.js setup & tests
      # ----------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/service/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      # ----------------------------
      # Static Application Security Testing (SAST)
      # ----------------------------
      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci

      - name: Security audit
        run: npm audit --audit-level=high

      # ----------------------------
      # AWS authentication (OIDC)
      # ----------------------------
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActions-ECR-Push
          aws-region: ${{ env.AWS_REGION }}

      # ----------------------------
      # Login to Amazon ECR
      # ----------------------------
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login \
            --username AWS \
            --password-stdin \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      # ----------------------------
      # Build Docker image
      # ----------------------------
      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/${ECR_REPOSITORY}
          echo "Building image: $ECR_URI:$IMAGE_TAG"
          docker build -f Dockerfile -t $ECR_URI:$IMAGE_TAG .

      # ----------------------------
      # Container Image Security Scan
      # ----------------------------
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.27.0
        with:
          image-ref: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          format: table
          exit-code: 1
          vuln-type: os,library
          severity: HIGH,CRITICAL

      # ----------------------------
      # Push Docker image to ECR
      # ----------------------------
      - name: Push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/${ECR_REPOSITORY}
          docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest
          docker push $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:latest
